-- Healthcare Provider Data Migration Case Study
-- Create Snowflake tables for legacy and migrated provider data.

CREATE OR REPLACE DATABASE HEALTHCARE_MIGRATION_DB;
CREATE OR REPLACE SCHEMA HEALTHCARE_MIGRATION_DB.PROVIDER_MIGRATION;
USE DATABASE HEALTHCARE_MIGRATION_DB;
USE SCHEMA PROVIDER_MIGRATION;

CREATE OR REPLACE TABLE LEGACY_PROVIDER (
    PROVIDER_ID STRING,
    NPI STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    PROVIDER_TYPE STRING,
    CREDENTIAL_STATUS STRING,
    LAST_UPDATED_DATE DATE
);

CREATE OR REPLACE TABLE SNOWFLAKE_PROVIDER (
    PROVIDER_ID STRING,
    NPI STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    PROVIDER_TYPE STRING,
    CREDENTIAL_STATUS STRING,
    LAST_UPDATED_DATE DATE
);

CREATE OR REPLACE TABLE LEGACY_PROVIDER_SPECIALTY (
    PROVIDER_ID STRING,
    SPECIALTY_CODE STRING,
    SPECIALTY_NAME STRING
);

CREATE OR REPLACE TABLE SNOWFLAKE_PROVIDER_SPECIALTY (
    PROVIDER_ID STRING,
    SPECIALTY_CODE STRING,
    SPECIALTY_NAME STRING
);

CREATE OR REPLACE TABLE LEGACY_PROVIDER_LOCATION (
    PROVIDER_ID STRING,
    ADDRESS_LINE1 STRING,
    CITY STRING,
    STATE STRING,
    ZIP STRING,
    PHONE STRING
);

CREATE OR REPLACE TABLE SNOWFLAKE_PROVIDER_LOCATION (
    PROVIDER_ID STRING,
    ADDRESS_LINE1 STRING,
    CITY STRING,
    STATE STRING,
    ZIP STRING,
    PHONE STRING
);

CREATE OR REPLACE TABLE LEGACY_CREDENTIALS (
    PROVIDER_ID STRING,
    LICENSE_NUMBER STRING,
    CREDENTIAL_STATUS STRING,
    CREDENTIAL_EXPIRY_DATE DATE
);

CREATE OR REPLACE TABLE SNOWFLAKE_CREDENTIALS (
    PROVIDER_ID STRING,
    LICENSE_NUMBER STRING,
    CREDENTIAL_STATUS STRING,
    CREDENTIAL_EXPIRY_DATE DATE
);
