-- Optional Snowflake loading pattern.
-- Update file paths/stage names for your environment.

USE DATABASE HEALTHCARE_MIGRATION_DB;
USE SCHEMA PROVIDER_MIGRATION;

CREATE OR REPLACE FILE FORMAT CSV_HEADER_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('', 'NULL', 'None');

CREATE OR REPLACE STAGE PROVIDER_MIGRATION_STAGE
FILE_FORMAT = CSV_HEADER_FORMAT;

-- Upload CSVs manually in Snowsight or with SnowSQL, then run COPY INTO commands.
-- Example:
-- PUT file://data/legacy_provider.csv @PROVIDER_MIGRATION_STAGE AUTO_COMPRESS=TRUE;

COPY INTO LEGACY_PROVIDER
FROM @PROVIDER_MIGRATION_STAGE/legacy_provider.csv.gz
FILE_FORMAT = CSV_HEADER_FORMAT;

COPY INTO SNOWFLAKE_PROVIDER
FROM @PROVIDER_MIGRATION_STAGE/snowflake_provider.csv.gz
FILE_FORMAT = CSV_HEADER_FORMAT;
