USE DATABASE HEALTHCARE_MIGRATION_DB;
USE SCHEMA PROVIDER_MIGRATION;

CREATE OR REPLACE VIEW MIGRATION_RECONCILIATION_SUMMARY AS
SELECT 'Row Count Difference' AS CHECK_NAME,
       ABS((SELECT COUNT(*) FROM LEGACY_PROVIDER) - (SELECT COUNT(*) FROM SNOWFLAKE_PROVIDER)) AS ISSUE_COUNT
UNION ALL
SELECT 'Missing Providers', COUNT(*)
FROM LEGACY_PROVIDER L
LEFT JOIN SNOWFLAKE_PROVIDER S ON L.PROVIDER_ID = S.PROVIDER_ID
WHERE S.PROVIDER_ID IS NULL
UNION ALL
SELECT 'Duplicate NPIs', COUNT(*)
FROM (
    SELECT NPI
    FROM SNOWFLAKE_PROVIDER
    GROUP BY NPI
    HAVING COUNT(*) > 1
)
UNION ALL
SELECT 'Credential Expiry Mismatches', COUNT(*)
FROM LEGACY_CREDENTIALS L
JOIN SNOWFLAKE_CREDENTIALS S ON L.PROVIDER_ID = S.PROVIDER_ID
WHERE L.CREDENTIAL_EXPIRY_DATE <> S.CREDENTIAL_EXPIRY_DATE
UNION ALL
SELECT 'Null Specialty Names', COUNT(*)
FROM SNOWFLAKE_PROVIDER_SPECIALTY
WHERE SPECIALTY_NAME IS NULL OR TRIM(SPECIALTY_NAME) = ''
UNION ALL
SELECT 'Invalid ZIP Codes', COUNT(*)
FROM SNOWFLAKE_PROVIDER_LOCATION
WHERE NOT REGEXP_LIKE(ZIP, '^[0-9]{5}$')
UNION ALL
SELECT 'Provider Status Mismatches', COUNT(*)
FROM LEGACY_PROVIDER L
JOIN SNOWFLAKE_PROVIDER S ON L.PROVIDER_ID = S.PROVIDER_ID
WHERE COALESCE(L.CREDENTIAL_STATUS, '') <> COALESCE(S.CREDENTIAL_STATUS, '');

SELECT * FROM MIGRATION_RECONCILIATION_SUMMARY;
