USE DATABASE HEALTHCARE_MIGRATION_DB;
USE SCHEMA PROVIDER_MIGRATION;

-- 1. Row count reconciliation
SELECT
    'PROVIDER' AS TABLE_NAME,
    (SELECT COUNT(*) FROM LEGACY_PROVIDER) AS LEGACY_COUNT,
    (SELECT COUNT(*) FROM SNOWFLAKE_PROVIDER) AS SNOWFLAKE_COUNT,
    (SELECT COUNT(*) FROM LEGACY_PROVIDER) - (SELECT COUNT(*) FROM SNOWFLAKE_PROVIDER) AS COUNT_DIFFERENCE;

-- 2. Missing provider records in Snowflake target
SELECT
    L.PROVIDER_ID,
    L.NPI,
    L.FIRST_NAME,
    L.LAST_NAME
FROM LEGACY_PROVIDER L
LEFT JOIN SNOWFLAKE_PROVIDER S
    ON L.PROVIDER_ID = S.PROVIDER_ID
WHERE S.PROVIDER_ID IS NULL;

-- 3. Duplicate NPI values in Snowflake target
SELECT
    NPI,
    COUNT(*) AS DUPLICATE_COUNT
FROM SNOWFLAKE_PROVIDER
GROUP BY NPI
HAVING COUNT(*) > 1;

-- 4. Credential expiry date mismatch
SELECT
    L.PROVIDER_ID,
    L.CREDENTIAL_EXPIRY_DATE AS LEGACY_EXPIRY_DATE,
    S.CREDENTIAL_EXPIRY_DATE AS SNOWFLAKE_EXPIRY_DATE,
    DATEDIFF('day', L.CREDENTIAL_EXPIRY_DATE, S.CREDENTIAL_EXPIRY_DATE) AS DATE_DIFFERENCE_DAYS
FROM LEGACY_CREDENTIALS L
JOIN SNOWFLAKE_CREDENTIALS S
    ON L.PROVIDER_ID = S.PROVIDER_ID
WHERE L.CREDENTIAL_EXPIRY_DATE <> S.CREDENTIAL_EXPIRY_DATE;

-- 5. Null or missing specialty names
SELECT
    S.PROVIDER_ID,
    S.SPECIALTY_CODE,
    S.SPECIALTY_NAME
FROM SNOWFLAKE_PROVIDER_SPECIALTY S
WHERE S.SPECIALTY_NAME IS NULL OR TRIM(S.SPECIALTY_NAME) = '';

-- 6. Invalid ZIP code format
SELECT
    PROVIDER_ID,
    ZIP
FROM SNOWFLAKE_PROVIDER_LOCATION
WHERE NOT REGEXP_LIKE(ZIP, '^[0-9]{5}$');

-- 7. Field-level mismatch check
SELECT
    L.PROVIDER_ID,
    L.PROVIDER_TYPE AS LEGACY_PROVIDER_TYPE,
    S.PROVIDER_TYPE AS SNOWFLAKE_PROVIDER_TYPE,
    L.CREDENTIAL_STATUS AS LEGACY_STATUS,
    S.CREDENTIAL_STATUS AS SNOWFLAKE_STATUS
FROM LEGACY_PROVIDER L
JOIN SNOWFLAKE_PROVIDER S
    ON L.PROVIDER_ID = S.PROVIDER_ID
WHERE COALESCE(L.PROVIDER_TYPE, '') <> COALESCE(S.PROVIDER_TYPE, '')
   OR COALESCE(L.CREDENTIAL_STATUS, '') <> COALESCE(S.CREDENTIAL_STATUS, '');

-- 8. Address formatting drift
SELECT
    L.PROVIDER_ID,
    L.ADDRESS_LINE1 AS LEGACY_ADDRESS,
    S.ADDRESS_LINE1 AS SNOWFLAKE_ADDRESS
FROM LEGACY_PROVIDER_LOCATION L
JOIN SNOWFLAKE_PROVIDER_LOCATION S
    ON L.PROVIDER_ID = S.PROVIDER_ID
WHERE L.ADDRESS_LINE1 <> S.ADDRESS_LINE1
  AND UPPER(L.ADDRESS_LINE1) = UPPER(S.ADDRESS_LINE1);
